server:
  port: 18002

spring:
  application:
    name: cloud-pay-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.61:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entity

# 配置eureka Client
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册在EurekaServer上，默认为true。
    fetch-registry: true #表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    serviceUrl:
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/

---
spring:
     profiles: pay18001