server:
  port: 18001

spring:
  application:
    name: cloud-pay-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bddadmin
    password: bddadmin-123456
    url: jdbc:mysql://rm-wz9nfogaze8qy137zco.mysql.rds.aliyuncs.com:3306/cloud2020?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entity

# 配置eureka Client
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册在EurekaServer上，默认为true。
    fetch-registry: true #表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    serviceUrl:
      defaultZone: http://eureka01.com:7001/eureka/,http://eureka02.com:7002/eureka/
  instance:
    instance-id: pay18001
    prefer-ip-address: true