server:
  port: 19003

spring:
  application:
    name: consul-consumer-pay
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}