spring:
  application:
    name: cloud-consumer-feign-hystrix-order
server:
  port: 19005
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01.com:7001/eureka/
feign:
  hystrix:
    enabled: true
