server:
  port: 19001
spring:
  application:
    name: cloud-consumer-order
# 配置eureka Client
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册在EurekaServer上，默认为true。
    fetch-registry: true #表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    serviceUrl:
      defaultZone: http://eureka02.com:7002/eureka/,http://eureka02.com:7002/eureka/