server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PAY-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**
            - After=2020-06-18T11:21:18.058+08:00[Asia/Shanghai]
#            - Cookie=username,huanfion
#            - Header=X-Request-Id, \d+
#            - Query=username,\d+
        - id: payment_routh
          uri: lb://CLOUD-PAY-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**

#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh #路由id，没有固定值但是保证唯一，建议配合服务名
#          uri: http://localhost:18001 #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/** #断言，路径相匹配的进行路由
#        - id: payment_routh2 #路由id，没有固定值但是保证唯一，建议配合服务名
#          uri: http://localhost:18001 #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb/** #断言，路径相匹配的进行路由
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01.com:7001/eureka/