server:
  port: 18001
spring:
  application:
    name: cloud-provider-hystrix-pay
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01.com:7001/eureka/