
spring:
  application:
    name: eureka-server
  profiles:
    active: eureka-01
---
spring:
  profiles: eureka-01
server:
  port: 7001
eureka:
  server:
    enable-self-preservation: false  # 开发环境关掉保护机制,快速发现已经挂掉的服务，生产环境需要设置为true提升服务稳定性
  instance:
    hostname: eureka01.com #192.168.50.79
    instance-id: eureka01.com:7001 #192.168.50.49:7001
    prefer-ip-address: false
  client:
    register-with-eureka: true #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    fetch-registry: true #表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    serviceUrl:
      defaultZone: http://eureka02.com:7002/eureka/
---
spring:
  profiles: eureka-02
server:
  port: 7002
eureka:
  server:
    enable-self-preservation: false  # 开发环境关掉保护机制,快速发现已经挂掉的服务，生产环境需要设置为true提升服务稳定性
  instance:
    hostname: eureka02.com #192.168.50.79
    instance-id: eureka02.com:7002 #192.168.50.49:7001
    prefer-ip-address: false
  client:
    register-with-eureka: true #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    fetch-registry: true #表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    serviceUrl:
      defaultZone: http://eureka01.com:7001/eureka/