FROM java:8
VOLUME /tmp
ADD target/warehouse-client-0.0.1-SNAPSHOT.jar /app.jar
RUN bash -c 'touch app.jar'
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/shanghai" > /etc/timezone
EXPOSE 9909
ENTRYPOINT ["java","-Dfile.encoding=UTF-8","-Djava.security.egd=file:/./urandom","-jar","/app.jar","--spring.profiles.active=client94"]